# SFM Flow Training Configuration
# This config is specifically for training Shallow Flow Matching (SFM) model
# without LLM initialization

# Global parameters
spk_embed_dim: 192
sfm_strength: 2.5  # SFM inference strength parameter alpha
sample_rate: 24000

# Feature extractor configuration
feat_extractor: !name:matcha.utils.audio.mel_spectrogram
    n_fft: 1920
    num_mels: 80
    sampling_rate: !ref <sample_rate>
    hop_size: 480
    win_size: 1920
    fmin: 0
    fmax: 8000
    center: False

# Main SFM Flow model
flow: !new:model.flow.flow.CausalMaskedDiffWithXvecSFM
    # Model dimensions
    input_size: 512
    output_size: 80
    spk_embed_dim: !ref <spk_embed_dim>
    vocab_size: 6561
    pre_lookahead_len: 3
    sfm_strength: !ref <sfm_strength>
    
    # Encoder configuration (UpsampleConformerEncoder)
    encoder: !new:cosyvoice.transformer.upsample_encoder.UpsampleConformerEncoder
        output_size: 512
        attention_heads: 8
        linear_units: 2048
        num_blocks: 6
        dropout_rate: 0.1
        positional_dropout_rate: 0.1
        attention_dropout_rate: 0.1
        normalize_before: True
        input_layer: 'linear'
        pos_enc_layer_type: 'rel_pos_espnet'
        selfattention_layer_type: 'rel_selfattn'
        input_size: 512
        use_cnn_module: False
        macaron_style: False
    
    # SFM Head configuration
    sfm_head: !new:model.flow.sfm_head.SFMHead
        d_hidden: 512       # Must match encoder output_size
        mel_channels: 80    # Must match flow output_size
        dropout_rate: 0.5
    
    # Decoder configuration (CausalConditionalCFM with SFM support)
    decoder: !new:model.flow.flow_matching.CausalConditionalCFM
        in_channels: 352    # 80 (mel) + 80 (coarse mel) + 192 (spk_emb) = 352
        n_spks: 1
        spk_emb_dim: 192    # Must match global spk_embed_dim
        cfm_params: !new:omegaconf.DictConfig
            content:
                sigma_min: 1e-06
                solver: 'euler'
                t_scheduler: 'cosine'
                training_cfg_rate: 0.2
                inference_cfg_rate: 0.7
                reg_loss_type: 'l1'
        estimator: !new:model.flow.decoder.CausalConditionalDecoder
            in_channels: 352  # Must match decoder in_channels
            out_channels: 80
            channels: [256]
            dropout: 0.0
            attention_head_dim: 64
            n_blocks: 4
            num_mid_blocks: 12
            num_heads: 8
            act_fn: 'gelu'
            static_chunk_size: 50
            num_decoding_left_chunks: 2 